# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: ${COMPOSE_PROJECT_NAME}-sql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2020"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  colour-api:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}-colour-api
    environment: 
      DBServer: "ms-sql-server"
    ports:
      - "5000:5000"
    depends_on:
        - "ms-sql-server"
  
  